In [1]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from ipywidgets import HBox, VBox, Button, Layout
from IPython.display import display
import numpy as np
from ipynb.fs.full.Functions import input_UFV, input_U, read_input
from openpyxl import load_workbook

['Example.UFVinp' 'Example.Uinp']
      k      Rk     Qk  V_k^(1)  V_k^(2)
CH3   1  0.9011  0.848        0        1
CH2   2  0.6744  0.540        0        1
CH    3  0.4469  0.228        0        1
CF3  74  1.4060  1.380        2        0
CF2  75  1.0105  0.920        6        0

[[  0.      0.      0.     -2.859  -2.859]
 [  0.      0.      0.     -2.859  -2.859]
 [  0.      0.      0.     -2.859  -2.859]
 [147.3   147.3   147.3     0.      0.   ]
 [147.3   147.3   147.3     0.      0.   ]]

a (b = 1 or 1.28 depending on hard core volume)
[5.36982678e+00 3.67807776e+00 1.77824323e+00 9.49365070e-01
 1.00818904e-01 1.01494607e-03]

vol_frac2
[0.90734935 0.95169757 0.98069972 0.9903533  0.99903564 0.99999036]

_________________________________________________
Flory-Huggins Parameter: 3.799755109327962
_________________________________________________
For j: 0
[['Diethylamine', ['CH3', ' CH2NH', ' CH2'], array([2, 1, 1]), 0.4], ['Heptane', ['CH3', ' CH2'], array([2, 5]), 0.6]]
Activity c

In [16]:
w_rho_S = widgets.FloatText(
    value=0.791,
    description=r'Density of Solvent $\left(\frac{g}{cm^3}\right)$:',
    style = {'description_width': 'initial'},
    disabled=False
)

w_rho_P = widgets.FloatText(
    value=0.865,
    description=r'Density of Polymer $\left(\frac{g}{cm^3}\right)$:',
    style = {'description_width': 'initial'},
    disabled=False
)
w_name_S = widgets.Text(
    value= 'CH3, CH3CO',
    description='Name of Solvent Groups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
w_name_P = widgets.Text(
    value= 'CH3, CH2, CH',
    description='Name of Polymer Groups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
w_vk_S = widgets.Text(
    value= '1, 1',
    description='Amount of Solvent Groups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
w_vk_P = widgets.Text(
    value= '1, 1, 1',
    description='Amount of Polymer Groups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
w_DP = widgets.FloatText(
    value=2000/42,
    description='Degree of Polymerization:',
    style = {'description_width': 'initial'},
    disabled=False
)
w_T = widgets.FloatText(
    value=25+273.15,
    description='Temperature (K):',
    style = {'description_width': 'initial'},
    disabled=False
)

# w_UFV = widgets.ToggleButton(
#     value=True,
#     description='UNIFAC-FV',
#     icon='check', 
#     style = {'description_width': 'initial'}
# )

# w_U = widgets.ToggleButton(
#     value=False,
#     description='UNIFAC',
#     icon='check', 
#     style = {'description_width': 'initial'}
# )

w_select = widgets.RadioButtons(
    options=['UNIFAC-FV', 'UNIFAC'],
    value='UNIFAC-FV', # Defaults to 'pineapple'
    layout={'width': 'max-content'}, # If the items' names are long
    description='Select Method:',
    style = {'description_width': 'max-content'},
    disabled=False
)

UFV_type = widgets.RadioButtons(
    options=['Solvent Weight Fraction', 'Solvent Volume Fraction', 'Polymer Weight Fraction', 'Polymer Volume Fraction'],
    value='Solvent Weight Fraction', # Defaults to 'pineapple'
    layout={'width': 'max-content'}, # If the items' names are long
    description='Select Type:',
    style = {'description_width': 'max-content'},
    disabled=False
)

w_Printed = widgets.ToggleButton(
    value=False,
    description='Print Extra Information',
    icon='check', 
    layout={'width': 'max-content'}
    #style = {'description_width': 'max-content'}
)

button = widgets.Button(
    description='Calculate',
)

error = widgets.Valid(
            value=False,
            #description='Valid: ',
)

solvent_num = widgets.IntText(
    value = 2,
    description='Number of Solvents:',
    style = {'description_width': 'initial'},
    disabled=False
)

wu_T = widgets.FloatText(
    value=308.15,
    description='Temperature (K):',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################

name_1 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_1 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_1 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_1 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_2 = widgets.Text(
    value= 'n-Heptane',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_2 = widgets.Text(
    value= 'CH3, CH2',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_2 = widgets.Text(
    value= '2, 5',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_2 = widgets.Text(
    value='0.6',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_3 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_3 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_3 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_3 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_4 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_4 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_4 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_4 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_5 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_5 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_5 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_5 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_6 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_6 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_6 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_6 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_7 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_7 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_7 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_7 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_8 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_8 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_8 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_8 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_9 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_9 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_9 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_9 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)

##########################
name_10 = widgets.Text(
    value= 'Diethylamine',
    description='Name of Solvent: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)
subgroup_10 = widgets.Text(
    value= 'CH3, CH2, CH2NH',
    description='Name of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

vk_10 = widgets.Text(
    value= '2, 1, 1',
    description='Amount of Subgroups: ', 
    style = {'description_width': 'initial'},
    layout={'width': '500px'} 
)

x_10 = widgets.Text(
    value='0.4',
    description='Mole fraction:',
    style = {'description_width': 'initial'},
    disabled=False
)
####################################################
Ulog_name = widgets.Text(
    value= 'Example_Name',
    description='Name of Log File:',
    style = {'description_width': 'initial'},
    layout={'width': '500px'}
)
UFVlog_name = widgets.Text(
    value= 'Example_Name',
    description='Name of Log File:',
    style = {'description_width': 'initial'},
    layout={'width': '500px'}
)
##########################
root_tab = VBox(children=[HBox(children = [w_select])])
root_T = widgets.Tab(children=[root_tab])
root_T.set_title(0, 'Select Method')

display(root_T)
##########################
u1_tab = VBox(children=[solvent_num, wu_T, w_Printed])
U_log = VBox(children=[Ulog_name])
u1_Tabed = widgets.Tab(children=[u1_tab, U_log])
u1_Tabed.set_title(0, 'System Properties')
u1_Tabed.set_title(1, 'Log Info')

##########################
UFV_select_tab1 = VBox(children=[UFV_type])
UFV_log = VBox(children=[UFVlog_name])
UFV_select = widgets.Tab(children=[UFV_select_tab1, UFV_log])
UFV_select.set_title(0, 'System Properties')
UFV_select.set_title(1, 'Log Info')
##########################
solvent1 = VBox(children=[name_1, subgroup_1, vk_1, x_1])
solvent2 = VBox(children=[name_2, subgroup_2, vk_2, x_2])
solvent3 = VBox(children=[name_3, subgroup_3, vk_3, x_3])
solvent4 = VBox(children=[name_4, subgroup_4, vk_4, x_4])
solvent5 = VBox(children=[name_5, subgroup_5, vk_5, x_5])
solvent6 = VBox(children=[name_6, subgroup_6, vk_6, x_6])
solvent7 = VBox(children=[name_7, subgroup_7, vk_7, x_7])
solvent8 = VBox(children=[name_8, subgroup_8, vk_8, x_8])
solvent9 = VBox(children=[name_9, subgroup_9, vk_9, x_9])
solvent10 = VBox(children=[name_10, subgroup_10, vk_10, x_10])

##########################
interact_calc = interact.options(manual=True, manual_name="Run")
@interact_calc
def Calculate():
    global w_select
    
#     if (w_U.value and w_UFV.value):
#         display(error)
#         print("Please select ONLY 1 method")
#         return
    ##########################
    if w_select.value == 'UNIFAC':
        display(u1_Tabed)
        interact_calc3 = interact.options(manual=True, manual_name="Run")
        @interact_calc3
        def SelectU():
            global solvent_num, wu_T, w_Printed
            solvent_n = solvent_num.value
            
            # This code below seems silly but I could not find a way in the widgets
            # documentation to make an expanding widget, since each widget is linked to its
            # value, so you can't simply display the same widget every time (or else they
            # will be linked)
            # There is a way to make a parent widget with multiple children but that seems
            # like it would overly complicate everything
            log_name = str(Ulog_name.value) + ".Ulog"
            file_log = open(log_name, "w")
            
            if solvent_n == 1:
                display(error)
                print("Please input more than 1 solvent")
                file_log.write("Please input more than 1 solvent.\n")
                file_log.write("Exited with errors.")
                file_log.close()
                return
            if solvent_n == 2:
                Solvents = widgets.Tab(children=[solvent1, solvent2])
            if solvent_n == 3:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3])
            if solvent_n == 4:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4])
            if solvent_n == 5:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4, solvent5])
            if solvent_n == 6:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4, solvent5, solvent6])
            if solvent_n == 7:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4, solvent5, solvent6, solvent7])
            if solvent_n == 8:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4, solvent5, solvent6, solvent7, solvent8])
            if solvent_n == 9:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4, solvent5, solvent6, solvent7, solvent8, solvent9])
            if solvent_n == 10:
                Solvents = widgets.Tab(children=[solvent1, solvent2, solvent3, solvent4, solvent5, solvent6, solvent7, solvent8, solvent9, solvent10])
            if solvent_n > 10:
                display(error)
                print("This widget is limited to 10 solvents, please use the function 'input_U' instead.")
                print("Alternatively, you can use the read_input() function to read from input files.")
            
            for i in range(0, solvent_n):
                solvent_tab_name = 'Sol. ' + str(i+1)
                Solvents.set_title(i, solvent_tab_name)
            display(Solvents)
            
            interact_calc3 = interact.options(manual=True, manual_name="Calculate")
            @interact_calc3
            def CalculateU():
                global name_1, subgroup_1, vk_1, x_1
                global name_2, subgroup_2, vk_2, x_2
                global name_3, subgroup_3, vk_3, x_3
                global name_4, subgroup_4, vk_4, x_4
                global name_5, subgroup_5, vk_5, x_5
                global name_6, subgroup_6, vk_6, x_6
                global name_7, subgroup_7, vk_7, x_7
                global name_8, subgroup_8, vk_8, x_8
                global name_9, subgroup_9, vk_9, x_9
                global name_10, subgroup_10, vk_10, x_10
                
                list_solvent = []
                if solvent_n >= 2:
                    list_solvent.append([name_1.value, subgroup_1.value, vk_1.value, x_1.value])
                    list_solvent.append([name_2.value, subgroup_2.value, vk_2.value, x_2.value])
                if solvent_n >= 3:
                    list_solvent.append([name_3.value, subgroup_3.value, vk_3.value, x_3.value])
                if solvent_n >= 4:
                    list_solvent.append([name_4.value, subgroup_4.value, vk_4.value, x_4.value])
                if solvent_n >= 5:
                    list_solvent.append([name_5.value, subgroup_5.value, vk_5.value, x_5.value])
                if solvent_n >= 6:
                    list_solvent.append([name_6.value, subgroup_6.value, vk_6.value, x_6.value])
                if solvent_n >= 7:
                    list_solvent.append([name_7.value, subgroup_7.value, vk_7.value, x_7.value])
                if solvent_n >= 8:
                    list_solvent.append([name_8.value, subgroup_8.value, vk_8.value, x_8.value])
                if solvent_n >= 9:
                    list_solvent.append([name_9.value, subgroup_9.value, vk_9.value, x_9.value])
                if solvent_n == 10:
                    list_solvent.append([name_10.value, subgroup_10.value, vk_10.value, x_10.value])
                
                #list_solvent = np.asarray(list_solvent)
                #print("Number of Solvents: " + str(len(list_solvent)))
                for i in range(0, len(list_solvent)):
                    #print(list_solvent[i])
                    s1 = str(list_solvent[i][1])
                    s1 = s1.replace("'", "")
                    s1 = s1.replace('"', "")
                    #print(list_solvent[i])
                    #print(s1)
                    s1 = s1.split(",")
                    #print(list_solvent[i])
                    #print(s1)
                    for j in range(0, len(s1)):
                        s1[j] = s1[j].strip()
                    #print(s1)
                    if not s1[0]:
                        display(error)
                        print("The number of subgroup names has to be greater than 0.")
                        file_log.write("The number of subgroup names has to be greater than 0.\n")
                        file_log.write("Exited with errors.")
                        file_log.close()
                        return
                    
                    list_solvent[i][1] = s1
                    
                    #print(list_solvent[i])
                    v1 = list_solvent[i][2]
                    #print(v1)
                    v1 = v1.split(",")
                    for j in range(0, len(v1)):
                        try:
                            v1[j] = int(v1[j].strip())
                        except ValueError:
                            display(error)
                            print("The number of subgroup amounts has to be greater than 0.")
                            file_log.write("The number of subgroup amounts has to be greater than 0.\n")
                            file_log.write("Exited with errors.")
                            file_log.close()
                            return
                    #print(v1)
                    list_solvent[i][2] = v1
                    
                    x1 = list_solvent[i][3]
                    #print(v1)
                    x1 = x1.split(",")
                    if not x1:
                        display(error)
                        print("The number of mole_fractions has to be greater than 0.")
                        file_log.write("The number of mole_fractions has to be greater than 0.\n")
                        file_log.write("Exited with errors.")
                        file_log.close()
                        return
                    x1 = (np.array(x1)).astype(float)
                            
                
                # Already checked in input_U, this is redundant
                """
                x_test = 0
                for i in range(0, len(list_solvent)):
                    x_test += float(list_solvent[i][3])
                
                if np.round(x_test, 3) != 1:
                    display(error)
                    print("Sum of mole fractions must equal 1.")
                    print("Currently it is: " + str(x_test))
                    file_log.write("Sum of mole fractions must equal 1.\n")
                    file_log.write("Currently it is: " + str(x_test)+ "\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return
                """
                
                
                
                activity_coef = []
                if len(list_solvent[0][3]) > 1:
                    coefs = np.zeros((len(list_solvent), len(list_solvent[0][3])))
                    mol_fractions = np.zeros((len(list_solvent), len(list_solvent[0][3])))
                    for i in range(0, len(list_solvent)):
                        mol_fractions[i][:] = list_solvent[i][3]

                    for i in range(0, len(mol_fractions[0][:])):
                        for j in range(0, len(list_solvent)):
                            list_solvent[j][3] = mol_fractions[j][i]
                        print("For j: " + str(i))
                        print(list_solvent)
                        warnings, coefficients = input_U(list_solvent, wu_T.value, w_Printed.value, file_log)

                        #print(coefficients)
                        if int(warnings) == -1:
                            file_log.write("Exited with errors.")
                            return
                        elif int(warnings) != -1:
                            for j in range(0, len(list_solvent)):
                                coefs[j][i] = coefficients[j]
                    for i in range(0, len(list_solvent)):
                        activity_coef.append(coefs[i][:])


                elif len(list_solvent[0][3]) == 1:
                    warnings, coefficients = input_U(list_solvent, wu_T.value, w_Printed.value, file_log)

                    if warnings != -1:
                        for i in range(0, len(list_solvent)):
                            activity_coef.append(coefficients[i])


                if int(warnings) == -1:
                    file_log.write("Exited with errors.")
                    return
                else:
                    # print out info here
                    for i in range(0, len(list_solvent)):
                        file_log.write("For " + str(list_solvent[i][0]) + ": \n")
                        file_log.write("Mole Fraction: " + str(mol_fractions[i]) + "\n")
                        file_log.write("Activity Coefficient: " + str(np.round(activity_coef[i],3)) + "\n")
                        file_log.write("\n")
                    if int(warnings) == 0:
                        # No errors or warnings
                        file_log.write("Exited with no errors or warnings.")
                    elif int(warnings) == 1:
                        file_log.write("Exited with 1 warning.")
                    elif int(warnings) >1:
                        file_log.write("Exited with " + str(int(warnings)) + " warnings.")
                    else:
                        file_log.write("Warnings not listed in possible options.\n")
                        file_log.write("Exited with errors.")
                file_log.close()
                
                return 
    ##########################  
    
    if w_select.value == 'UNIFAC-FV':
        display(UFV_select)
        interact_calc4 = interact.options(manual=True, manual_name="Run")
        @interact_calc4
        def SelectUFV():
            global UFV_type, UFV_frac
            
            UFV_frac = widgets.Text(
                value= '0.09575, 0.05, 0.02, 0.01, 0.001, 0.00001',
                #description='Fraction (of Previosuly Selected Type): ', 
                description= UFV_type.value + ": ", 
                style = {'description_width': 'initial'},
                layout={'width': '500px'} 
            )

            ##########################
            tab1 = VBox(children=[w_name_S, w_vk_S, w_rho_S])
            tab2 = VBox(children=[w_name_P, w_vk_P, w_rho_P, w_DP])
            tab3 = VBox(children=[w_T, UFV_frac])
            tab = widgets.Tab(children=[tab1, tab2, tab3])
            tab.set_title(0, 'Solvent')
            tab.set_title(1, 'Polymer')
            tab.set_title(2, 'System')

            VBox(children=[tab, button])
            #display(tab)
            ##########################
            
            display(tab)
            interact_calc2 = interact.options(manual=True, manual_name="Calculate")
            @interact_calc2
            def CalculateUFV():
                global w_name_S, w_vk_S, w_rho_S, w_name_P, w_vk_P, w_rho_P, w_DP, w_T
                
                log_name = str(UFVlog_name.value) + ".UFVlog"
                file_log = open(log_name, "w")
                name_S = str(w_name_S.value).replace("'", "")
                name_S = name_S.replace('"', "")
                name_S = name_S.split(",")
                if not name_S[0]:
                    display(error)
                    print("Error in Solvent Input.")
                    print("Subgroup name is blank.")
                    file_log.write("Error in Solvent Input.\n")
                    file_log.write("Subgroup name is blank.\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return
                name_P = str(w_name_P.value).replace("'", "")
                name_P = name_P.replace('"', "")
                name_P = name_P.split(",")
                if not name_P[0]:
                    display(error)
                    print("Error in Polymer Input.")
                    print("Subgroup name is blank.")
                    file_log.write("Error in Polymer Input.\n")
                    file_log.write("Subgroup name is blank.\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return
                name_S = np.array(name_S)
                name_P = np.array(name_P)
                vk_S = str(w_vk_S.value).split(",")
                vk_S = np.array(vk_S)
                if not vk_S[0]:
                    display(error)
                    print("Error in Solvent Input.")
                    print("Subgroup amount is blank.")
                    file_log.write("Error in Solvent Input.\n")
                    file_log.write("Subgroup amount is blank.\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return
                vk_S = vk_S.astype(int)
                vk_P = str(w_vk_P.value).split(",")
                vk_P = np.array(vk_P)
                if not vk_P[0]:
                    display(error)
                    print("Error in Polymer Input.")
                    print("Subgroup amount is blank.")
                    file_log.write("Error in Polymer Input.\n")
                    file_log.write("Subgroup amount is blank.\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return
                vk_P = vk_P.astype(int)

                name_S = name_S.tolist()
                vk_S = vk_S.tolist()
                name_P = name_P.tolist()
                vk_P = vk_P.tolist()
                #print(name_S)
                #print(type(name_S))
                
                # fractions 
                frac = str(UFV_frac.value).split(",")
                frac = np.array(frac)
                if not frac[0]:
                    display(error)
                    print(frac)
                    print("Error in " + str(UFV_type.value) + " Input.")
                    print(str(UFV_type.value) + " is blank.")
                    file_log.write("Error in " + str(UFV_type.value) + " Input.\n")
                    file_log.write(str(UFV_type.value) + " is blank.\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return
                frac = frac.astype(float)
                
                if UFV_type.value == 'Solvent Weight Fraction':
                    frac_type = 1
                elif UFV_type.value == 'Solvent Volume Fraction':
                    frac_type = 2
                elif UFV_type.value == 'Polymer Weight Fraction':
                    frac_type = 3
                elif UFV_type.value == 'Polymer Volume Fraction':
                    frac_type = 4
                else:
                    display(error)
                    print("Fraction type not selected.")
                    file_log.write("Fraction type not selected.\n")
                    file_log.write("Exited with errors.")
                    file_log.close()
                    return 
     
                warnings, x, a1_b = input_UFV(name_S, name_P, vk_S, vk_P, w_rho_S.value, w_rho_P.value, w_DP.value, w_T.value, frac, frac_type, file_log)
                
                if int(warnings) == -1:
                    file_log.write("Exited with errors.")
                    return
                else:
                    # print out info here
                    file_log.write("Polymer Group Names: " + str(name_P) + "\n")
                    file_log.write("Polymer Density (g/cm^3): " + str(w_rho_P.value) +"\n")
                    file_log.write("Solvent Group Names: " + str(name_S) + "\n")
                    file_log.write("Solvent Density (g/cm^3): " + str(w_rho_S.value) +"\n")
                    file_log.write("Degree of Polymerization: " + str(np.round(w_DP.value, 3)) + "\n")
                    file_log.write("Temperature (K): " + str(w_T.value) + "\n")
                    file_log.write(str(UFV_type.value) + ": " + str(frac) + "\n")
                    file_log.write("Activities: " + str(a1_b) + "\n")
                    file_log.write("Flory-Huggins Parameter: " + str(np.round(x,3)) + "\n")
                    if int(warnings) == 0:
                        # No errors or warnings
                        file_log.write("Exited with no errors or warnings.")
                    elif int(warnings) == 1:
                        file_log.write("Exited with 1 warning.")
                    elif int(warnings) >1:
                        file_log.write("Exited with " + str(int(warnings)) + " warnings.")
                    else:
                        file_log.write("Warnings not listed in possible options.\n")
                        file_log.write("Exited with errors.")
                file_log.close()
        
                return
            return

interactive(children=(Button(description='Run', style=ButtonStyle()), Output()), _dom_classes=('widget-interac…

In [11]:
solvents = []

# Example diethylamine(1)/n-heptane(2)

# Define solvent 1: 
# diethylamine = CH 3 − CH 2 NH − CH 2 − CH 3
# subgroups, k:   1        32       2      1
# amounts: CH3 appears twice = 2, CH2 appears once = 1, CH2NH appears once = 1
d_names = ['CH3', 'CH2NH', 'CH2']
d_vk = [2, 1, 1] # Amount of times each shows up
x_d = 0.4 # Mole fraction

diethylamine = ["Diethylamine", d_names, d_vk, x_d]
solvents.append(diethylamine)
# Define solvent 2:
# n-heptane =    CH 3 − ( CH 2 ) 5 − CH 3 
# subgroups, k:    1        2          1
# amounts: CH3 appears twice = 2, CH2 appears 5 times

h_names = ['CH3', 'CH2']

h_vk = [2, 5] # Amount of times each shows up
x_h = 0.6 # Mole fraction

heptane = ["n-heptane", h_names, h_vk, x_h]
solvents.append(heptane)

# System parameters
T = 308.15 # Kelvin

# Prints out extra information (Mainly used in debugging)
printed = False
#print(solvents)

file_log = open("Example_Func.Ulog", 'w')
warnings, coefficients = input_U(solvents, T, printed, file_log)

Activity coefficient for Diethylamine: 1.1330392999346754
Activity coefficient for n-heptane: 1.0470238738018751


In [5]:
# UNIFAC-FV EXAMPLE:

# PFO  (SOLVENT)
# Perfluorooctane
# CF3 CF2 CF2 CF2 CF2 CF2 CF2 CF3
#   F F F F F F F F
# F C C C C C C C C F
#   F F F F F F F F
#
# Amounts: CF3 appears 2 times, CF2 appears 6 times
name_S = ['CF2', 'CF3'] # names of subgroups
# For list of subgroups please check excel file
# MAKE SURE NAMES ARE CORRECT CH3CO =/= COCH3

vk_S = [6, 2] # amounts
rho_S = 0.897 # density (g/cm^3)

################################################

# POLYPROPYLENE (POLYMER)
# CH3 
# CH CH2
#       H
#   H - C - H    H
# -     C    -   C -
#       H        H
# Amounts: CH3 appears 1 time, CH2 appears 1 time, CH appears 1 time
# Note: When dealing with polymers only put amount of times a group appears in the
# monomer

name_P = ['CH3', 'CH', 'CH2'] 
vk_P = [1, 1, 1]
rho_P = 0.865 # density (g/cm^3)

DP = 2000/42 # Degree of polymerization = number of monomers per polymer molecule

T = 25 + 273.15 # K

frac = [0.09575, 0.05, 0.02, 0.01, 0.001, 0.00001]
frac_type = 1 # Solvent Weight Fraction
file_log = open("Example_Func.UFVlog", 'w')
input_UFV(name_S, name_P, vk_S, vk_P, rho_S, rho_P, DP, T, frac, frac_type, file_log)

      k      Rk     Qk  V_k^(1)  V_k^(2)
CH3   1  0.9011  0.848        0        1
CH2   2  0.6744  0.540        0        1
CH    3  0.4469  0.228        0        1
CF3  74  1.4060  1.380        2        0
CF2  75  1.0105  0.920        6        0

[[  0.      0.      0.     -2.859  -2.859]
 [  0.      0.      0.     -2.859  -2.859]
 [  0.      0.      0.     -2.859  -2.859]
 [147.3   147.3   147.3     0.      0.   ]
 [147.3   147.3   147.3     0.      0.   ]]

a (b = 1 or 1.28 depending on hard core volume)
[5.36982678e+00 3.67807776e+00 1.77824323e+00 9.49365070e-01
 1.00818904e-01 1.01494607e-03]

vol_frac2
[0.90734935 0.95169757 0.98069972 0.9903533  0.99903564 0.99999036]

_________________________________________________
Flory-Huggins Parameter: 3.799755559148784
_________________________________________________


(0,
 3.799755559148784,
 array([5.36982678e+00, 3.67807776e+00, 1.77824323e+00, 9.49365070e-01,
        1.00818904e-01, 1.01494607e-03]))

In [ ]:
# TODO 
# There is a way to serialize widgets (i.e. make a parent widget and have multiple childeren)
# ^ Make your code do this instead of the bad way you're doing now
# ^ Really annoying and no one needs more than 10, leave as is
# Automatically order input (i.e. Subgroup names, Vk) by increasing subgroup number k 
# ^ Fixed <- NOT for UNIFAC just for UNIFAC-FV
#                ^ FIXED

# ADD Error checks < DONE
# Make generic UFV--> Weight and volume fraction
#

# maybe add error due to log, due to density issue

In [ ]:
print(0%2 == 0)
print(2%2 == 0)